applications:
  argo-cd:
    annotations:
      argocd.argoproj.io/sync-wave: "20"
    destination:
      namespace: argo-system
    source:
      path: clusters/omv/apps/argo-system/argo-cd

  renovate:
    annotations:
      argocd.argoproj.io/sync-wave: "20"
    destination:
      namespace: default
    source:
      path: components/default/renovate

  holmesgpt:
    annotations:
      argocd.argoproj.io/sync-wave: "20"
    destination:
      namespace: ai
    source:
      path: components/ai/holmesgpt

  rancher:
    annotations:
      argocd.argoproj.io/sync-wave: "20"
    destination:
      namespace: cattle-system
    source:
      path: components/cattle-system/rancher

  valkey:
    annotations:
      argocd.argoproj.io/sync-wave: "20"
    destination:
      namespace: default
    source:
      path: components/default/valkey
