---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./externalsecret.yaml
  - ./http-route.yaml
  - ./networkpolicy.yaml
  - ./rbac.yaml
  - ./servicemonitor.yaml
helmCharts:
  - name: app-template
    releaseName: agent-farm
    namespace: ai
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "5.1.0"
    valuesFile: values.yaml
