---
controllers:
  app:
    replicas: 1
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      init-db:
        image:
          repository: ghcr.io/home-operations/postgres-init
          tag: 18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
        envFrom: &envFrom
          - secretRef:
              name: atuin-secret
    containers:
      app:
        image:
          repository: ghcr.io/atuinsh/atuin
          tag: 18.16.1@sha256:9d4d79507b51be6d292b218f5cc791d79ca0a72f51ab48f786b091bd6eafb39f
        env:
          ATUIN_HOST: 0.0.0.0
          ATUIN_PORT: &port 80
          ATUIN_OPEN_REGISTRATION: "true"
          ATUIN_METRICS__ENABLE: "true"
          ATUIN_METRICS__HOST: 0.0.0.0
          ATUIN_METRICS__PORT: &metricsPort 8080
          ATUIN_TLS__ENABLE: "false"
        envFrom: *envFrom
        args: ["start"]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 256Mi
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
service:
  app:
    ports:
      http:
        port: *port
      metrics:
        port: *metricsPort
serviceMonitor:
  app:
    serviceName: app
    enabled: true
    endpoints:
      - port: metrics
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
persistence:
  config:
    enabled: true
    type: emptyDir
