---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-runner-docker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-volsync
  resources:
    requests:
      storage: 25Gi
