---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-agent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-agent-secret
    template:
      engineVersion: v2
      data:
        HERMES_API_KEY: "{{ .INFERENCE_HUB_API_KEY }}"
        HERMES_BASE_URL: "{{ .INFERENCE_HUB_BASE_URL }}"
        TELEGRAM_BOT_TOKEN: "{{ .TELEGRAM_BOT_TOKEN_HERMES }}"
        TELEGRAM_ALLOWED_USERS: "{{ .TELEGRAM_ALLOWED_USER_ID }}"
        HERMES_WORKSPACE_PASSWORD: "{{ .HERMES_WORKSPACE_PASSWORD }}"
        .env: |-
          HERMES_API_KEY={{ .INFERENCE_HUB_API_KEY }}
          HERMES_BASE_URL={{ .INFERENCE_HUB_BASE_URL }}
          TELEGRAM_BOT_TOKEN={{ .TELEGRAM_BOT_TOKEN_HERMES }}
          TELEGRAM_ALLOWED_USERS={{ .TELEGRAM_ALLOWED_USER_ID }}
  dataFrom:
    - extract:
        key: inference-hub
    - extract:
        key: ivan
    - extract:
        key: hermes
