---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hermes-cluster-reader
rules:
  - apiGroups: [""]
    resources:
      - events
      - namespaces
      - nodes
      - persistentvolumeclaims
      - pods
      - services
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["get", "list"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list"]
  - apiGroups: ["events.k8s.io"]
    resources:
      - events
    verbs: ["get", "list"]
  - apiGroups: ["argoproj.io"]
    resources:
      - applications
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hermes-cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hermes-cluster-reader
subjects:
  - kind: ServiceAccount
    name: hermes-cluster-reader
    namespace: ai
