---
controllers:
  app:
    type: cronjob
    cronjob:
      schedule: "0 3 * * *"
      timeZone: America/New_York
      concurrencyPolicy: Forbid
      successfulJobsHistory: 3
      failedJobsHistory: 3
      backoffLimit: 1
      ttlSecondsAfterFinished: 604800
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      restartPolicy: Never
    containers:
      app:
        image:
          repository: ghcr.io/renovatebot/renovate
          tag: "43.243.2@sha256:9e7084cd44ac8be22639b08c15d81617c2f2c9b9188f062d522a2a696984ef26"
        env:
          RENOVATE_CONFIG_FILE: /config/config.js
          LOG_LEVEL: info
        envFrom:
          - secretRef:
              name: renovate-secret
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

persistence:
  config:
    enabled: true
    type: configMap
    name: renovate-config
    globalMounts:
      - path: /config
        readOnly: true
  cache:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /tmp/renovate
  tmp:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /tmp
