---
controllers:
  app:
    type: cronjob
    cronjob:
      schedule: "0 3 * * *"
      timeZone: America/New_York
      concurrencyPolicy: Forbid
      successfulJobsHistory: 3
      failedJobsHistory: 3
      backoffLimit: 1
      ttlSecondsAfterFinished: 604800
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      restartPolicy: Never
    containers:
      app:
        image:
          repository: ghcr.io/renovatebot/renovate
          tag: "44.96.1@sha256:4fb5632bf40175cc35a90c831e7c552ce0ab13e73527e5384fb1f8ec79033dc4"
        env:
          RENOVATE_CONFIG_FILE: /config/config.js
          LOG_LEVEL: info
        envFrom:
          - secretRef:
              name: renovate-secret
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

persistence:
  config:
    enabled: true
    type: configMap
    name: renovate-config
    globalMounts:
      - path: /config
        readOnly: true
  cache:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /tmp/renovate
  tmp:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /tmp
