---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vikunja-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Vikunja database config
        VIKUNJA_DATABASE_HOST: postgres17-rw.default.svc.cluster.local
        VIKUNJA_DATABASE_DATABASE: vikunja
        VIKUNJA_DATABASE_USER: "{{ .POSTGRES_USER }}"
        VIKUNJA_DATABASE_PASSWORD: "{{ .POSTGRES_PASS }}"

        # Vikunja API token for ivan integration
        VIKUNJA_SERVICE_JWTSECRET: "{{ .JWT_SECRET }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: vikunja
        INIT_POSTGRES_HOST: postgres17-rw.default.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: vikunja
    - extract:
        key: cloudnative-pg
