---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ivan-os
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ivan-os-secret
    template:
      engineVersion: v2
      data:
        TELEGRAM_BOT_TOKEN: "{{ .TELEGRAM_BOT_TOKEN }}"
        TELEGRAM_ALLOWED_USER_ID: "{{ .TELEGRAM_ALLOWED_USER_ID }}"
        NVIDIA_API_KEY: "{{ .INFERENCE_HUB_API_KEY }}"
        GITEA_TOKEN: "{{ .IVAN_TOKEN }}"
        GITEA_URL: "https://gitea.omv.${CLUSTER_DOMAIN}"
        GITEA_USER: "vpogu"
        GITEA_REPO_URL: "https://gitea.omv.${CLUSTER_DOMAIN}/vpogu/ivan-os.git"
        IVAN_OS_DATABASE_URL: |-
          postgres://{{ .IVAN_POSTGRES_USER }}:{{ .IVAN_POSTGRES_PASS }}@postgres17-rw.default.svc.cluster.local/ivan_os
        # Postgres Init
        INIT_POSTGRES_DBNAME: ivan_os
        INIT_POSTGRES_HOST: postgres17-rw.default.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .IVAN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .IVAN_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: ivan
    - extract:
        key: inference-hub
    - extract:
        key: gitea
    - extract:
        key: cloudnative-pg
