---
controllers:
  app:
    replicas: 1
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      init-db:
        image:
          repository: ghcr.io/home-operations/postgres-init
          tag: 18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
        envFrom: &envFrom
          - secretRef:
              name: reactive-resume-secret
    containers:
      chrome:
        image:
          repository: ghcr.io/browserless/chromium
          tag: v2.18.0 # Upgrading to newer versions causes issues
        env:
          TIMEOUT: 10000
          CONCURRENT: 10
          TOKEN: chrome_token
          EXIT_ON_HEALTH_FAILURE: "true"
          PRE_REQUEST_HEALTH_CHECK: "true"
      app:
        image:
          repository: amruthpillai/reactive-resume
          tag: v5.2.1@sha256:49086173f0cfe17889ad3082db89405bdd5907330fb5cab6c179512259e03900
        env:
          PORT: &port 8080
          NODE_ENV: production

          # -- URLs --
          APP_URL: https://reactive-resume.${CLUSTER_DOMAIN}
          PUBLIC_URL: http://localhost:8080

          # -- Printer (Chrome) --
          CHROME_TOKEN: chrome_token
          CHROME_URL: ws://localhost:3000
          STORAGE_ENDPOINT: garage-s3.default.svc.cluster.local
          STORAGE_PORT: 3900
          STORAGE_REGION: garage # Optional
          STORAGE_BUCKET: reactive-resume
          STORAGE_USE_SSL: "false"
          STORAGE_SKIP_BUCKET_CHECK: "false"
          DISABLE_SIGNUPS: "true"
          DISABLE_EMAIL_AUTH: "false"
        envFrom: *envFrom
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 750Mi
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  app:
    ports:
      http:
        port: *port
