---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./namespace.yaml
  - ./externalsecret.yaml
  - ./http-route.yaml
  - ./scheduled-healthchecks.yaml

helmCharts:
  - name: holmes
    releaseName: holmesgpt
    namespace: ai
    repo: https://robusta-charts.storage.googleapis.com
    version: 0.32.0
    valuesFile: values.yaml
    includeCRDs: true
