---
controllers:
  garage-s3-backup:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-5-1u
    containers:
      app:
        image:
          repository: dxflrs/garage
          tag: v2.3.0@sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690
        env:
          TZ: "America/New_York"
          GARAGE_ADMIN_TOKEN:
            valueFrom:
              secretKeyRef:
                name: garage-s3-backup-secret
                key: GARAGE_ADMIN_TOKEN
          GARAGE_RPC_SECRET:
            valueFrom:
              secretKeyRef:
                name: garage-s3-backup-secret
                key: GARAGE_RPC_SECRET
          GARAGE_METRICS_TOKEN:
            valueFrom:
              secretKeyRef:
                name: garage-s3-backup-secret
                key: GARAGE_METRICS_TOKEN
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            memory: 2Gi

service:
  app:
    controller: garage-s3-backup
    ports:
      rpc:
        port: 3901
      s3:
        port: 3900
      api:
        port: 3903

persistence:
  disk1:
    type: hostPath
    hostPath: /var/mnt/backup1
    hostPathType: Directory
    globalMounts:
      - path: /storage/disk1
  disk2:
    type: hostPath
    hostPath: /var/mnt/backup2
    hostPathType: Directory
    globalMounts:
      - path: /storage/disk2
  disk3:
    type: hostPath
    hostPath: /var/mnt/backup3
    hostPathType: Directory
    globalMounts:
      - path: /storage/disk3
  disk4:
    type: hostPath
    hostPath: /var/mnt/backup4
    hostPathType: Directory
    globalMounts:
      - path: /storage/disk4
  disk5:
    type: hostPath
    hostPath: /var/mnt/backup5
    hostPathType: Directory
    globalMounts:
      - path: /storage/disk5
  disk6:
    type: hostPath
    hostPath: /var/mnt/backup6
    hostPathType: Directory
    globalMounts:
      - path: /storage/disk6
  disk7:
    type: hostPath
    hostPath: /var/mnt/backup7
    hostPathType: Directory
    globalMounts:
      - path: /storage/disk7
  disk8:
    type: hostPath
    hostPath: /var/mnt/backup8
    hostPathType: Directory
    globalMounts:
      - path: /storage/disk8
  config:
    type: configMap
    name: garage-s3-backup-configmap
    globalMounts:
      - path: /etc/garage.toml
        subPath: configuration.toml
