---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: volsync
  namespace: volsync-system
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: https
      scheme: http
  selector:
    matchLabels:
      control-plane: volsync-controller
