---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ivan-personal-service
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ivan-personal-service-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: >-
          postgres://{{ .IVAN_POSTGRES_USER }}:{{ .IVAN_POSTGRES_PASS }}@postgres17-rw.default.svc.cluster.local:5432/ivan_personal
        INIT_POSTGRES_DBNAME: ivan_personal
        INIT_POSTGRES_HOST: postgres17-rw.default.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .IVAN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .IVAN_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        ACTUAL_BUDGET_PASSWORD: "{{ .ACTUAL_API_KEY }}"
        ACTUAL_BUDGET_SYNC_ID: "{{.SYNC_ID}}"
        SYNOLOGY_USER: "{{ .SYNOLOGY_USERNAME }}"
        SYNOLOGY_PASSWORD: "{{ .SYNOLOGY_PASSWORD }}"
        GOG_ACCOUNT: "{{ .GOG_DEFAULT_ACCOUNT }}"
        YOUTUBE_API_KEY: "{{ .YOUTUBE_API_KEY }}"
        PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_KEY }}"
        PAPERLESS_API_URL: "https://paperless.${CLUSTER_DOMAIN}/api"
        GOOGLE_CLIENT_ID: "{{ .GOOGLE_CLIENT_ID }}"
        GOOGLE_CLIENT_SECRET: "{{ .GOOGLE_CLIENT_SECRET }}"
        GOOGLE_REFRESH_TOKEN: "{{ .GOOGLE_REFRESH_TOKEN }}"
        GOOGLE_PLACES_API_KEY: "{{ .GOOGLE_PLACES_API_KEY }}"
        UNIFI_HOST: "https://{{.UNIFI_HOST}}"
        UNIFI_API_KEY: "{{.IVAN_AGENT_API_KEY}}"
        PROMETHEUS_URL: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
        HOME_ASSISTANT_TOKEN: "{{.IVAN_HASS_TOKEN}}"
        OBSIDIAN_S3_BUCKET: "obsidian-notes"
        AWS_ACCESS_KEY_ID: "{{.MAIN_ACCESS_KEY}}"
        AWS_SECRET_ACCESS_KEY: "{{.MAIN_SECRET_KEY}}"
        AWS_DEFAULT_REGION: "{{.REGION}}"
        AWS_ENDPOINT_URL: "http://garage-s3.default.svc.cluster.local:3900"
        INFERENCE_HUB_BASE_URL: "{{ .INFERENCE_HUB_BASE_URL }}"
        API_KEY: "{{ .INFERENCE_HUB_API_KEY }}"
        IVAN_PERSONAL_HERMES_API_KEY: "{{ .IVAN_PERSONAL_API_KEY }}"
        IVAN_PERSONAL_DASHBOARD_API_KEY: "{{ .IVAN_PERSONAL_DASHBOARD_API_KEY }}"
  dataFrom:
    - extract:
        key: inference-hub
    - extract:
        key: ivan
    - extract:
        key: cloudnative-pg
    - extract:
        key: Github
    - extract:
        key: gitea
    - extract:
        key: unifi
    - extract:
        key: home-assistant
    - extract:
        key: garage
    - extract:
        key: actual
    - extract:
        key: synology-vikas
    - extract:
        key: paperless
    - extract:
        key: unifi
    - extract:
        key: home-assistant
    - extract:
        key: garage
