---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ivan-personal-service
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ivan-personal-service-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: >-
          postgres://{{ .IVAN_POSTGRES_USER }}:{{ .IVAN_POSTGRES_PASS }}@postgres17-rw.default.svc.cluster.local:5432/ivan_personal
        INIT_POSTGRES_DBNAME: ivan_personal
        INIT_POSTGRES_HOST: postgres17-rw.default.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .IVAN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .IVAN_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        HOME_ASSISTANT_TOKEN: "{{ .IVAN_HASS_TOKEN }}"
        ACTUAL_BUDGET_PASSWORD: "{{ .ACTUAL_API_KEY }}"
        ACTUAL_BUDGET_SYNC_ID: "{{.SYNC_ID}}"
        PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_KEY }}"
        SYNOLOGY_USER: "{{ .SYNOLOGY_USERNAME }}"
        SYNOLOGY_PASSWORD: "{{ .SYNOLOGY_PASSWORD }}"
        GOG_ACCOUNT: "{{ .GOG_DEFAULT_ACCOUNT }}"
        YOUTUBE_API_KEY: "{{ .YOUTUBE_API_KEY }}"
  dataFrom:
    - extract:
        key: ivan
    - extract:
        key: cloudnative-pg
    - extract:
        key: Github
    - extract:
        key: gitea
    - extract:
        key: unifi
    - extract:
        key: home-assistant
    - extract:
        key: garage
    - extract:
        key: actual
    - extract:
        key: synology-vikas
    - extract:
        key: paperless
