---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mac
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mac-secret
    template:
      engineVersion: v2
      data:
        MAC_DATABASE_URL: "postgresql://mac:{{ .MAC_POSTGRES_PASSWORD }}@postgres17-rw.default.svc.cluster.local:5432/mac"
        MAC_PG_POOL_SIZE: "20"
        MAC_SECRET_KEY: "{{ .MAC_SECRET_KEY }}"
        MAC_WORKER_TOKEN: "{{ .MAC_WORKER_TOKEN }}"
        MAC_API_TOKENS: '{"{{ .MAC_WORKER_TOKEN }}": ["admin"]}'
        INFERENCE_HUB_API_KEY: "{{ .INFERENCE_HUB_API_KEY }}"
        INIT_POSTGRES_HOST: postgres17-rw.default.svc.cluster.local
        INIT_POSTGRES_DBNAME: mac
        INIT_POSTGRES_USER: mac
        INIT_POSTGRES_PASS: "{{ .MAC_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        GH_TOKEN: "{{ .MAC_TOKEN }}"
        GITEA_TOKEN: "{{ .IVAN_TOKEN }}"
        GITEA_USER: "vpogu"
  dataFrom:
    - extract:
        key: mac
    - extract:
        key: cloudnative-pg
    - extract:
        key: inference-hub
    - extract:
        key: Github
    - extract:
        key: gitea
