---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./externalsecret.yaml
  - ./rbac.yaml
  - ./http-route.yaml

helmCharts:
  - name: app-template
    releaseName: mac
    namespace: ai
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "5.0.1"
    valuesFile: values.yaml
configMapGenerator:
  - name: mac-config
    files:
      - config.yaml=config.yaml
    options:
      disableNameSuffixHash: true
  - name: mac-opencode-config
    files:
      - opencode.json
    options:
      disableNameSuffixHash: true
