---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-cleanup
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitea-cleanup-secret
    template:
      engineVersion: v2
      data:
        api-token: "{{ .IVAN_TOKEN }}"
  dataFrom:
    - extract:
        key: gitea
