---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kopia-s3-secret
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .MAIN_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MAIN_SECRET_KEY }}"
        S3_ENDPOINT: "garage-s3.default.svc.cluster.local:3900"
        S3_BUCKET: "kopia-backup"
  dataFrom:
    - extract:
        key: garage
