---
controllers:
  app:
    pod:
      annotations:
        reloader.stakater.com/auto: "true"
      nodeSelector:
        kubernetes.io/hostname: k8s-4-dell
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 100
    initContainers:
      copy-config:
        image:
          repository: ghcr.io/home-operations/kopia
          tag: 0.23.0@sha256:76865b421548b1d7bb26a8268f0f0bc828be4eec3f8d8b9c8ece991c99878f94
        command: ["sh", "-c", "cp /config-ro/repository.config /config/repository.config"]
      chown-repo:
        image:
          repository: public.ecr.aws/docker/library/busybox
          tag: 1.38.0
        command: ["chown", "-R", "1000:1000", "/repository"]
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
            add: ["CHOWN", "FOWNER", "DAC_OVERRIDE", "DAC_READ_SEARCH"]
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/kopia
          tag: 0.23.0@sha256:76865b421548b1d7bb26a8268f0f0bc828be4eec3f8d8b9c8ece991c99878f94
        env:
          KOPIA_WEB_ENABLED: true
          KOPIA_WEB_PORT: &port 80
          TZ: "America/New_York"
        envFrom:
          - secretRef:
              name: kopia-secret
        args:
          - --without-password
          - --disable-csrf-token-checks
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 1Gi
service:
  app:
    ports:
      http:
        port: *port
      metrics:
        enabled: true
        port: 8080

serviceMonitor:
  app:
    enabled: false
    serviceName: app
    endpoints:
      - port: metrics
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s

persistence:
  config-ro:
    enabled: true
    type: configMap
    name: kopia-repository-configmap
    globalMounts:
      - path: /config-ro/repository.config
        subPath: repository.config
        readOnly: true
  config:
    type: emptyDir
    globalMounts:
      - path: /config
  repository:
    type: hostPath
    hostPath: /var/mnt/media/.kopia
    globalMounts:
      - path: /repository
