---
defaultPodOptions:
  enableServiceLinks: false
  nodeSelector:
    kubernetes.io/hostname: k8s-4-dell
controllers:
  jellyfin:
    strategy: Recreate
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: jellyfin/jellyfin
          tag: 10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
        env:
          DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
          JELLYFIN_FFmpeg__probesize: 50000000
          JELLYFIN_FFmpeg__analyzeduration: 50000000
          TZ: America/New_York
          NVIDIA_VISIBLE_DEVICES: all
          NVIDIA_DRIVER_CAPABILITIES: all
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
            nvidia.com/gpu: 1
          limits:
            memory: 6Gi
            nvidia.com/gpu: 1
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: &port 8096
              initialDelaySeconds: 0
              periodSeconds: 30
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false

service:
  app:
    ports:
      http:
        port: *port

persistence:
  config:
    enabled: true
    existingClaim: jellyfin
    globalMounts:
      - path: /config
  transcode:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /transcode
  media:
    type: hostPath
    hostPath: /var/mnt/media
    globalMounts:
      - path: /nfs-nas-pvc
