---
apiVersion: v1
kind: Secret
metadata:
  name: ivan-reader-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: ivan-reader
type: kubernetes.io/service-account-token
