metadata_dir = "/storage/meta"

# Single-disk configuration on existing backup-garage volume
data_dir = [
  { path = "/storage/data", capacity = "3TB" },
]

db_engine = "sqlite"
metadata_fsync = true
metadata_auto_snapshot_interval = "1h"

replication_factor = 1

compression_level = 2

rpc_bind_addr = "[::]:3901"
# Public address using Service FQDN
rpc_public_addr = "garage-s3.default.svc.cluster.local:3901"
rpc_secret = "${GARAGE_RPC_SECRET}"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "${GARAGE_ADMIN_TOKEN}"
