apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ntfy-secret
    creationPolicy: Owner
  data:
    - secretKey: NTFY_AUTH_USERS
      remoteRef:
        key: ntfy
        property: NTFY_AUTH_USERS
    - secretKey: NTFY_AUTH_TOKENS
      remoteRef:
        key: ntfy
        property: NTFY_AUTH_TOKENS
