---
controllers:
  app:
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 100
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      init-db:
        image:
          repository: ghcr.io/home-operations/postgres-init
          tag: 18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
        envFrom: &envFrom
          - secretRef:
              name: home-assistant-secret
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/home-assistant
          tag: 2026.7.3@sha256:7a6951bc274d802206d9ab2e76885fec8ba4f41707ae31d81207ebe5c73b84fb
        env:
          TZ: "America/New_York"
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            memory: 2500Mi
      codeserver:
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.129.0@sha256:49d5e176224523b0c924ee35b05c51e9a87f9c170f650ee0f7da05a4581a79ff
          pullPolicy: IfNotPresent
        env:
          TZ: "America/New_York"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
          - --port
          - "12321"
          - "/config"

service:
  app:
    ports:
      http:
        port: 8123
  codeserver:
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 12321
        protocol: TCP
        targetPort: 12321

persistence:
  config:
    enabled: true
    existingClaim: home-assistant
