---
controllers:
  app:
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 100
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      init-db:
        image:
          repository: ghcr.io/home-operations/postgres-init
          tag: 18.6.0@sha256:b6d3af974df781c673d37e49bdddfa14a6f5be28b18d2cb7713f0449bea4057b
        envFrom: &envFrom
          - secretRef:
              name: home-assistant-secret
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/home-assistant
          tag: 2026.9.1@sha256:1bcf770d15bd91a55491d04f12494febb35da68b025e1f6612a167a2e190a8c7
        env:
          TZ: "America/New_York"
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            memory: 2500Mi
      codeserver:
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.135.0@sha256:ccd326184d71efc5ebb94155eda7bb30153902342a35dbc8525450d81aa55012
          pullPolicy: IfNotPresent
        env:
          TZ: "America/New_York"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
          - --port
          - "12321"
          - "/config"

service:
  app:
    ports:
      http:
        port: 8123
  codeserver:
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 12321
        protocol: TCP
        targetPort: 12321

persistence:
  config:
    enabled: true
    existingClaim: home-assistant
