---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forge
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forge-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: >-
          postgres://{{ .FORGE_POSTGRES_USER }}:{{ .FORGE_POSTGRES_PASS }}@postgres17-rw.default.svc.cluster.local:5432/forge
        INIT_POSTGRES_DBNAME: forge
        INIT_POSTGRES_HOST: postgres17-rw.default.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .FORGE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .FORGE_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        OPENSHELL_TOKEN: "{{ .OPENSHELL_TOKEN }}"
        GH_TOKEN: "{{ .K8S_TOKEN }}"
        GITEA_TOKEN: "{{ .IVAN_TOKEN }}"
        GITEA_TOKEN_RO: "{{ .IVAN_TOKEN_RO }}"
        INFERENCE_HUB_BASE_URL: "{{ .INFERENCE_HUB_BASE_URL }}"
        INFERENCE_HUB_API_KEY: "{{ .INFERENCE_HUB_CODING_KEY }}"
        FORGE_INTAKE_TOKEN: "{{.FORGE_INTAKE_TOKEN}}"
        FORGE_UI_KEY: "{{.FORGE_UI_KEY}}"
        FORGE_OIDC_CLIENT_SECRET: "{{ .CLIENT_SECRET }}"
        FORGE_OIDC_CLIENT_ID: "{{ .CLIENT_ID }}"
        FORGE_OIDC_SYSTEM_OWNER_SUB: "{{ .FORGE_OIDC_SYSTEM_OWNER_SUB }}"
        FORGE_AUTH_SECRET: "{{ .FORGE_AUTH_SECRET }}"
        TELEGRAM_BOT_TOKEN: "{{.TELEGRAM_BOT_TOKEN}}"
        TELEGRAM_DEFAULT_CHAT_ID: "{{.TELEGRAM_DEFAULT_CHAT_ID}}"
  dataFrom:
    - extract:
        key: forge
    - extract:
        key: cloudnative-pg
    - extract:
        key: inference-hub
    - extract:
        key: Github
    - extract:
        key: gitea
    - extract:
        key: openshell
    - extract:
        key: ivan
