# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./externalsecret.yaml
  - ./configmap.yaml
  - ./rbac.yaml

helmCharts:
  - name: app-template
    releaseName: forge-orchestrator
    namespace: ai
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "5.1.0"
    valuesFile: values.yaml
