---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
helmCharts:
  - name: tempo
    releaseName: tempo
    namespace: observability
    repo: oci://ghcr.io/grafana-community/helm-charts
    version: 2.2.3
    valuesFile: values.yaml
