apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-runner-base
spec:
  source:
    registry:
      url: docker://quay.io/containerdisks/ubuntu@sha256:b6e57f3b59a34915587f6d8de671c4fe27397807789eeb96b972f3fa2f2107e1
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: ceph-block
