githubConfigUrl: https://github.com/Vikaspogu/home-ops
githubConfigSecret: github-arc-secret
controllerServiceAccount:
  namespace: actions-runner-system
  name: arc-controller-gha-rs-controller

runnerScaleSetName: kubevirt
minRunners: 0
maxRunners: 1

listenerTemplate:
  spec:
    containers:
      - name: listener
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi

template:
  spec:
    serviceAccountName: kubevirt-actions-runner
    containers:
      - name: runner
        image: docker.io/electrocucaracha/kubevirt-actions-runner@sha256:5c4ecf8e489afbe9a215c2ecaf0fb4342d47dac935b538b9952fceb735a596e1
        command: []
        env:
          - name: KUBEVIRT_VM_TEMPLATE
            value: ubuntu-runner
          - name: KUBEVIRT_VM_TEMPLATE_NAMESPACE
            value: actions-runners
          - name: RUNNER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KAR_WAIT_TIMEOUT
            value: 30m
          - name: KAR_CLEANUP_TIMEOUT
            value: 5m
          - name: KAR_TELEMETRY_ENABLED
            value: "true"
          - name: KAR_TELEMETRY_EXPORT_TYPE
            value: otlp
          - name: KAR_TELEMETRY_OTLP_ENDPOINT
            value: http://alloy.observability.svc.cluster.local:4318
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
