---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: gitea-apps
  namespace: argo-system
spec:
  namespace: argo-system
  commonUpdateSettings:
    updateStrategy: latest
    ignoreTags:
      - latest
  writeBackConfig:
    method: "git:secret:argo-system/git-creds"
    gitConfig:
      branch: main
  applicationRefs:
    - namePattern: "ivan"
      writeBackConfig:
        method: "git:secret:argo-system/git-creds"
        gitConfig:
          branch: main
          writeBackTarget: "helmvalues:./values.yaml"
      images:
        - alias: ivan
          imageName: "gitea.omv.${CLUSTER_DOMAIN}/vpogu/ivan-agent-v3"
          commonUpdateSettings:
            allowTags: 'regexp:^[0-9]{14}-[a-f0-9]{7}'
          manifestTargets:
            helm:
              name: controllers.app.containers.main.image.repository
              tag: controllers.app.containers.main.image.tag
        - alias: ivan-repo-worker
          imageName: "gitea.omv.${CLUSTER_DOMAIN}/vpogu/ivan-repo-worker"
          commonUpdateSettings:
            allowTags: 'regexp:^[0-9]{14}-[a-f0-9]{7}'
          manifestTargets:
            helm:
              name: controllers.app.containers.main.env.REPO_WORKER_IMAGE_REPOSITORY
              tag: controllers.app.containers.main.env.REPO_WORKER_IMAGE_TAG
    - namePattern: "ivan-os"
      writeBackConfig:
        method: "git:secret:argo-system/git-creds"
        gitConfig:
          branch: main
          writeBackTarget: "helmvalues:./values.yaml"
      images:
        - alias: ivan-os-api
          imageName: "gitea.omv.${CLUSTER_DOMAIN}/vpogu/ivan-os"
          commonUpdateSettings:
            allowTags: 'regexp:^[a-f0-9]{12}$'
            updateStrategy: latest
          manifestTargets:
            helm:
              name: controllers.app.containers.api.image.repository
              tag: controllers.app.containers.api.image.tag
        - alias: ivan-os-telegram
          imageName: "gitea.omv.${CLUSTER_DOMAIN}/vpogu/ivan-os"
          commonUpdateSettings:
            allowTags: 'regexp:^[a-f0-9]{12}$'
            updateStrategy: latest
          manifestTargets:
            helm:
              name: controllers.app.containers.telegram.image.repository
              tag: controllers.app.containers.telegram.image.tag
    - namePattern: "ivan-dashboard"
      writeBackConfig:
        method: "git:secret:argo-system/git-creds"
        gitConfig:
          branch: main
          writeBackTarget: "helmvalues:./values.yaml"
      images:
        - alias: dashboard-api
          imageName: "gitea.omv.${CLUSTER_DOMAIN}/vpogu/ivan-dashboard-api"
          commonUpdateSettings:
            allowTags: 'regexp:^[0-9]{14}-[a-f0-9]{7}'
          manifestTargets:
            helm:
              name: controllers.api.containers.main.image.repository
              tag: controllers.api.containers.main.image.tag
        - alias: dashboard-ui
          imageName: "gitea.omv.${CLUSTER_DOMAIN}/vpogu/ivan-dashboard-ui"
          commonUpdateSettings:
            allowTags: 'regexp:^[0-9]{14}-[a-f0-9]{7}'
          manifestTargets:
            helm:
              name: controllers.ui.containers.main.image.repository
              tag: controllers.ui.containers.main.image.tag
