apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-photos-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: synology-photos-backup-secret
    template:
      engineVersion: v2
      data:
        RCLONE_S3_ACCESS_KEY_ID: "{{ .MAIN_ACCESS_KEY }}"
        RCLONE_S3_SECRET_ACCESS_KEY: "{{ .MAIN_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: garage
