---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-ngx-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_DBHOST: &dbHost postgres17-rw.default.svc.cluster.local
        PAPERLESS_DBNAME: &dbName paperless
        PAPERLESS_DBUSER: &dbUser "{{ .PAPERLESS_DBUSER }}"
        PAPERLESS_DBPASS: &dbPass "{{ .PAPERLESS_DBPASS }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "Authentik",
                  "client_id": "{{ .CLIENT_ID }}",
                  "secret": "{{ .CLIENT_SECRET }}",
                  "settings": {
                    "server_url": "https://id.${CLUSTER_DOMAIN}/application/o/paperless-ngx/.well-known/openid-configuration"
                  }
                }
              ],
              "OAUTH_PKCE_ENABLED": "True"
            }
          }
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: cloudnative-pg
