apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: t3-orbit-ingress
spec:
  podSelector:
    matchLabels:
      agent-farm.io/workspace: acac5578e380aa52
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: network
          podSelector:
            matchLabels:
              gateway.envoyproxy.io/owning-gateway-name: envoy-internal
      ports:
        - protocol: TCP
          port: 3773
