apiVersion: v1
kind: Service
metadata:
  name: t3-orbit
spec:
  type: ClusterIP
  selector:
    agent-farm.io/workspace: acac5578e380aa52
  ports:
    - name: http
      port: 3773
      targetPort: 3773
      protocol: TCP
