---
defaultPodOptions:
  nodeSelector:
    kubernetes.io/hostname: k8s-4-dell
controllers:
  app:
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 100
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/sonarr
          tag: 4.0.17.2969@sha256:1989718e9fceb3fd35b4e73f61696c68f8959b8f09981cf137fdef8e6338b85f
        env:
          TZ: "America/New_York"
          SONARR__INSTANCE_NAME: Sonarr
          SONARR__PORT: &port 80
          SONARR__LOG_LEVEL: info
        resources:
          requests:
            cpu: 15m
            memory: 381M
          limits:
            memory: 2000Mi
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes

service:
  app:
    ports:
      http:
        port: *port
persistence:
  config:
    enabled: true
    existingClaim: sonarr
  media:
    type: hostPath
    hostPath: /var/mnt/media
    globalMounts:
      - path: /nfs-nas-pvc
