---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: trek-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        OIDC_CLIENT_ID: "{{ .CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: trek
