---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-http-api
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actual-http-api-secret
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .API_KEY }}"
        ACTUAL_SERVER_PASSWORD: "{{ .ACTUAL_SERVER_PASSWORD }}"
  dataFrom:
    - extract:
        key: actual-http-api
