---
controllers:
  valkey:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: valkey/valkey
          tag: 9.0.3-alpine@sha256:84c96f47ebe197e635cd3ddbe3ab74e8bdf783cf3befbfb1c36387275c1cd5d5
        env:
          VALKEY_PASSWORD_FILE: /secret/valkey-password
          VALKEY_PORT: &port 6379
service:
  app:
    ports:
      http:
        port: *port

persistence:
  data:
    type: emptyDir
  secret:
    type: secret
    name: valkey-secret
    advancedMounts:
      valkey:
        app:
          - path: /secret/valkey-password
            subPath: valkey-password
            readOnly: true
