---
controllers:
  valkey:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: valkey/valkey
          tag: 9.1.2-alpine@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11
        command:
          - sh
          - -c
          - |
            valkey-server \
              --port 6379 \
              --dir /data \
              --save "300 1" \
              --save "60 100"
        env:
          VALKEY_PORT: &port 6379
        probes:
          startup:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: *port
              initialDelaySeconds: 5
              periodSeconds: 5
          liveness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: *port
              periodSeconds: 30
service:
  app:
    ports:
      http:
        port: *port

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /data
  secret:
    type: secret
    name: valkey-secret
    advancedMounts:
      valkey:
        app:
          - path: /secret/valkey-password
            subPath: valkey-password
            readOnly: true
