apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-actions-runner
  namespace: actions-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevirt-actions-runner
  namespace: actions-runners
rules:
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachineinstances"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevirt-actions-runner
  namespace: actions-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevirt-actions-runner
subjects:
  - kind: ServiceAccount
    name: kubevirt-actions-runner
    namespace: actions-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-actions-runner-cdi-cloner
rules:
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes/source"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevirt-actions-runner-cdi-cloner
  namespace: actions-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-actions-runner-cdi-cloner
subjects:
  - kind: ServiceAccount
    name: kubevirt-actions-runner
    namespace: actions-runners
