---
defaultPodOptions:
  nodeSelector:
    kubernetes.io/hostname: k8s-4-dell
controllers:
  app:
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 100
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/radarr
          tag: 6.4.3.10645@sha256:0ebb4ae26ee9522674a4ad1855e926fd6b97c534ff982644c9c9a87bca740077
        env:
          TZ: "America/New_York"
          RADARR__INSTANCE_NAME: Radarr
          RADARR__PORT: &port 80
          RADARR__LOG_LEVEL: info
        resources:
          limits:
            memory: 1500Mi
          requests:
            cpu: 250m
            memory: 350Mi
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
service:
  app:
    ports:
      http:
        port: 80

persistence:
  config:
    enabled: true
    existingClaim: radarr
  media:
    type: hostPath
    hostPath: /var/mnt/media
    globalMounts:
      - path: /nfs-nas-pvc
