---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./externalsecret.yaml
helmCharts:
  - name: app-template
    releaseName: garage-s3-node2
    namespace: default
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.6.2"
    valuesFile: values.yaml
configMapGenerator:
  - name: garage-s3-node2-configmap
    files:
      - configuration.toml=./resources/configuration.toml
generatorOptions:
  disableNameSuffixHash: true
