---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recall
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: recall-secret
    template:
      engineVersion: v2
      data:
        RECALL_DATABASE_URL: |-
          postgresql+asyncpg://{{ .RECALL_POSTGRES_USER }}:{{ .RECALL_POSTGRES_PASS }}@postgres17-rw.default.svc.cluster.local/recall
        RECALL_SECRET_KEY: "{{ .RECALL_SECRET_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: recall
        INIT_POSTGRES_HOST: postgres17-rw.default.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .RECALL_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .RECALL_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: recall
    - extract:
        key: cloudnative-pg
