controllers:
  app:
    replicas: 1
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      init-db:
        image:
          repository: ghcr.io/home-operations/postgres-init
          tag: 18.3.0@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
        envFrom: &envFrom
        - secretRef:
            name: recall-secret
    containers:
      main:
        image:
          repository: gitea.omv.a113.casa/vpogu/recall-api
          tag: 20260311004831-0ea2ad5
          pullPolicy: IfNotPresent
        env:
          TZ: America/New_York
        envFrom: *envFrom
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 512Mi
        probes:
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/health
                port: &port 8000
              initialDelaySeconds: 5
              periodSeconds: 5
              failureThreshold: 30
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/health
                port: *port
              periodSeconds: 30
              failureThreshold: 3
    pod:
      imagePullSecrets:
      - name: gitea-registry-secret
service:
  app:
    controller: app
    ports:
      http:
        port: *port
