---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: cattle-system
  labels:
    app.kubernetes.io/instance: rancher
    app.kubernetes.io/name: rancher
spec:
  repo: https://releases.rancher.com/server-charts/stable
  chart: rancher
  targetNamespace: cattle-system
  valuesContent: |-
    hostname: "rancher.${CLUSTER_DOMAIN}"
    replicas: 1
    rancherImageTag: v2.13.3
    ingress:
      enabled: false
    tls: external
    agentTLSMode: "system-store"
    extraEnv:
      - name: CATTLE_FEATURES
        value: "fleet=false"
