---
worker:
  config:
    core:
      # NVIDIA GPU Operator requires the system source to select OS-specific workloads from system-os_release.ID.
      sources: ["custom", "pci", "system", "usb"]
    sources:
      usb:
        deviceClassWhitelist: ["02", "03", "0e", "ef", "fe", "ff"]
        deviceLabelFields: ["class", "vendor", "device"]
prometheus:
  enable: true
