---
apiVersion: coroot.com/v1
kind: Coroot
metadata:
  name: coroot
spec:
  metricsRefreshInterval: 15s
  cacheTTL: 30d
  tracesTTL: 7d
  logsTTL: 7d
  profilesTTL: 7d
  communityEdition:
    image:
      name: ghcr.io/coroot/coroot:v1.23.3
  externalPrometheus:
    url: http://prometheus-prometheus.observability.svc.cluster.local:9090
    remoteWriteURL: http://prometheus-prometheus.observability.svc.cluster.local:9090/api/v1/write
  clickhouse:
    shards: 1
    replicas: 1
    storage:
      size: 100Gi
      className: ceph-block
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 2Gi
    keeper:
      replicas: 1
      storage:
        size: 10Gi
        className: ceph-block
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
  clusterAgent:
    image:
      name: ghcr.io/coroot/coroot-cluster-agent:1.7.1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
  nodeAgent:
    image:
      name: ghcr.io/coroot/coroot-node-agent:1.34.2
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 256Mi
