---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filebrowser
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: filebrowser-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        FILEBROWSER_ADMIN_PASSWORD: "{{ .FILEBROWSER_ADMIN_PASSWORD }}"
        FILEBROWSER_JWT_TOKEN_SECRET: "{{ .FILEBROWSER_JWT_TOKEN_SECRET }}"
  dataFrom:
    - extract:
        key: filebrowser
