---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forge-system
resources:
  - namespace.yaml
helmCharts:
  - name: zot
    releaseName: zot
    namespace: forge-system
    repo: https://zotregistry.dev/helm-charts
    version: 0.1.122
    valuesFile: values.yaml
