---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ivan-repo-worker
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ivan-repo-worker-secret
    template:
      engineVersion: v2
      data:
        INFERENCE_HUB_MODEL: "{{ .INFERENCE_HUB_MODEL }}"
        INFERENCE_HUB_BASE_URL: "{{ .INFERENCE_HUB_BASE_URL }}"
        API_KEY: "{{ .INFERENCE_HUB_API_KEY }}"
        GH_TOKEN: "{{ .K8S_TOKEN }}"
        GITEA_TOKEN: "{{ .IVAN_TOKEN }}"
        GITEA_URL: "https://gitea.omv.${CLUSTER_DOMAIN}"
        GITEA_USER: "vpogu"
        DATABASE_URL: |-
          postgres://{{ .IVAN_POSTGRES_USER }}:{{ .IVAN_POSTGRES_PASS }}@postgres17-rw.default.svc.cluster.local/ivan
  dataFrom:
    - extract:
        key: inference-hub
    - extract:
        key: ivan
    - extract:
        key: cloudnative-pg
    - extract:
        key: Github
    - extract:
        key: gitea
