---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - external-secret.yaml
  - external-secret-repo-worker.yaml
  - external-secret-kc.yaml
components:
  - ../../volsync-system/volsync-replication
helmCharts:
  - name: app-template
    releaseName: ivan
    namespace: ai
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "5.0.0"
    valuesFile: values.yaml
