---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: pvc-backup
  namespace: storage
  labels:
    backup_type: pvc_only
spec:
  schedule: "*/30 * * * *"  # Every 30min
  useOwnerReferencesInBackup: false
  template:
    ttl: 24h  # 30 days retention
    storageLocation: default
    includedNamespaces:
      - storage
    includedResources:
      - persistentvolumeclaims
      - persistentvolumes
    snapshotVolumes: true

