---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kopia-maintenance
spec:
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: k8s-4-dell
          containers:
            - name: maintenance
              volumeMounts:
                - name: repository
                  mountPath: /repository
          volumes:
            - name: repository
              hostPath:
                path: /var/mnt/media/.kopia
                type: Directory
