---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openshell-db
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openshell-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        uri: >-
          postgres://{{ .OPENSHELL_POSTGRES_USER }}:{{ .OPENSHELL_POSTGRES_PASS }}@postgres17-rw.default.svc.cluster.local:5432/openshell
        INIT_POSTGRES_DBNAME: openshell
        INIT_POSTGRES_HOST: postgres17-rw.default.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .OPENSHELL_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .OPENSHELL_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: openshell
    - extract:
        key: cloudnative-pg
