# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./sandbox-namespace.yaml
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./networkpolicy-client.yaml
  - ./reflect-client-tls.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: openshell
      spec:
        template:
          spec:
            initContainers:
              - name: init-db
                image: ghcr.io/home-operations/postgres-init:18.6.0@sha256:b6d3af974df781c673d37e49bdddfa14a6f5be28b18d2cb7713f0449bea4057b
                envFrom:
                  - secretRef:
                      name: openshell-db-secret
            containers:
              - name: openshell-gateway
                volumeMounts:
                  - name: state
                    mountPath: /.local/state/openshell
            volumes:
              - name: state
                persistentVolumeClaim:
                  claimName: openshell-state
helmCharts:
  - name: helm-chart
    releaseName: openshell
    namespace: ai
    repo: oci://ghcr.io/nvidia/openshell
    version: "0.0.111"
    valuesFile: values.yaml
    includeCRDs: false
