---
controllers:
  it-tools:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/corentinth/it-tools
          tag: 2024.10.22-7ca5933
        env:
          TZ: America/New_York
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 500Mi
service:
  app:
    ports:
      http:
        port: 80
