---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
helmCharts:
  - name: coroot-operator
    releaseName: coroot-operator
    namespace: observability
    repo: https://coroot.github.io/helm-charts
    version: 0.9.7
    includeCRDs: true
    valuesFile: values.yaml
