---
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    memory: 128Mi
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
