---
kind: Deployment
deschedulerPolicyAPIVersion: descheduler/v1alpha2
deschedulerPolicy:
  profiles:
    - name: Default
      pluginConfig:
        - name: DefaultEvictor
          args:
            nodeFit: true
            noEvictionPolicy: Mandatory
            podProtections:
              defaultDisabled:
                - FailedBarePods
        - name: RemoveFailedPods
          args:
            reasons:
              - ContainerStatusUnknown
              - NodeAffinity
              - NodeShutdown
              - Terminated
              - UnexpectedAdmissionError
            includingInitContainers: true
            excludeOwnerKinds:
              - Job
            minPodLifetimeSeconds: 1800
        - name: RemovePodsViolatingInterPodAntiAffinity
        - name: RemovePodsViolatingNodeAffinity
          args:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        - name: RemovePodsViolatingTopologySpreadConstraint
        - name: RemoveDuplicates
      plugins:
        balance:
          enabled:
            - RemovePodsViolatingTopologySpreadConstraint
            - RemoveDuplicates
        deschedule:
          enabled:
            - RemoveFailedPods
            - RemovePodsViolatingInterPodAntiAffinity
            - RemovePodsViolatingNodeAffinity
service:
  enabled: true
serviceMonitor:
  enabled: true
leaderElection:
  enabled: true
